[package]
name = "forora"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramhorns = "0.5"

[dev-dependencies]
tempdir = "0.3"
uuid = { version = "0.8", features = ["v4"] }